language: go
sudo: false

go:
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - go vet
  - go test -race
  - $HOME/gopath/bin/goveralls -service=travis-ci
